name: Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
      - DOR*
      - feature/*
      - fix/*

jobs:
  run_build:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
          
      - name: Check node version
        run: node --version
        
      - name: Install dependencies 
        run: yarn install
      

      - name: Run linter
        run: yarn lint
        working-directory: ./

      - name: Build
        run: yarn build

