name: Coverage
on:
  pull_request:
    branches:
      - main
      - DOR*
      - feature/*
      - fix/*
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                output: report-markdown 
                annotations: all
                test-script: yarn jest
                package-manager: yarn
                working-directory: ./src

